hpc <- read.table("household_power_consumption.txt", header=FALSE, sep=";", na.strings = "?", skip=66637, nrows=2880,colClasses = c("character", "character", "numeric", "NULL", "NULL", "NULL", "NULL", "NULL", "NULL"))
hpc <- list(strptime(paste(hpc$V1,hpc$V2), format="%d/%m/%Y %H:%M:%S"), hpc$V3)
names(hpc) <- c("DateTime", "GlobalActivePower")
png("plot2.png")
plot(hpc$DateTime, hpc$GlobalActivePower, type="l", xlab="", ylab="Global Active Power (kilowatts)")
dev.off()